# Site settings
title: Howon Song
email: howon@songhowon.com
description: "Howon Song: web/mobile developer, author of Instant Music, admin of TogetherJS, CS major at Cornell"
baseurl: ""
url: "http://songhowon.com"

# Build settings
markdown: kramdown
permalink: pretty
